server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/cardsdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

build:
  version: 1.0.0

accounts:
  message: "Welcome to the Cards Service"
  contactDetails:
    name: "Cards Support"
    email: "cards.support@nimbus.com"