server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/cardsdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  application:
    name: cards
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

build:
  version: 1.0.0

accounts:
  message: "Welcome to the Cards Service"
  contactDetails:
    name: "Cards Support"
    email: "cards.support@nimbus.com"