version: '3.8'
services:
  accounts:
    image: "thehashmap/accounts:latest"
    container_name: accounts-service
    ports:
      - "8080:8080"
    depends_on: []
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - nimbus
  cards:
    image: "thehashmap/cards:latest"
    container_name: cards-service
    ports:
      - "9000:9000"
    depends_on: []
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - nimbus
  loans:
    image: "thehashmap/loans:latest"
    container_name: loans-service
    ports:
      - "8090:8090"
    depends_on: []
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - nimbus
networks:
  nimbus:
    driver: "bridge"
