server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/loansdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

build:
  version: 1.0.0

accounts:
  message: "Welcome to the Loans Service"
  contactDetails:
    name: "Loans Support"
    email: "loans.support@nimbus.com"